# Generated by Django 5.1.15 on 2026-04-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicearea",
            name="pincodes",
        ),
        migrations.AddField(
            model_name="servicearea",
            name="districts",
            field=models.TextField(
                default="", help_text="Comma separated district names"
            ),
        ),
        migrations.AlterField(
            model_name="servicearea",
            name="name",
            field=models.CharField(
                help_text="State name, e.g. Uttar Pradesh", max_length=100
            ),
        ),
    ]
